language: generic
sudo: required

services:
  - 'docker'
before_install:
  - docker build -f ./client/Dockerfile.dev -t unbiasedeagle/react-test ./client

script:
  - docker run -e CI=true unbiasedeagle/react-test npm run test

after_success:
  - docker build -t unbiasedeagle/multi-client:latest ./client
  - docker build -t unbiasedeagle/multi-server:latest ./server
  - docker build -t unbiasedeagle/multi-worker:latest ./worker
  - docker build -t unbiasedeagle/multi-nginx:latest ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push unbiasedeagle/multi-client:latest
  - docker push unbiasedeagle/multi-server:latest
  - docker push unbiasedeagle/multi-nginx:latest
  - docker push unbiasedeagle/multi-worker:latest
